---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
    groups:
      - centos
  - name: ubuntu1604
    image: ubuntu:16.04
provisioner:
  name: ansible
  inventory:
    group_vars:
      # Because CentOS is a docker container and doesn't include
      # systemd, we must ensure the service task is skipped
      centos:
        sysstat_service_enable: false
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
