---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true

    - name: Install cron
      yum:
        name: cronie
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
      become: true
